sudo: false
language: generic

compiler:
  - gcc

addons:
  apt:
    packages:
      - valgrind
  homebrew:
    update: true
    packages:
      - php@7.3

env:
  global:
    - REPORT_EXIT_STATUS=1
    - TEST_PHP_ARGS="-q --show-diff"

matrix:
  fast_finish: true
  include:
    - os: osx

before_install:
  - pip install --user cpp-coveralls

script:
  - phpize
  - wget -q -O run-tests.php https://raw.githubusercontent.com/php/php-src/master/run-tests.php
  - ./configure
  - make test-coverage

after_success:
  - coveralls -b $TRAVIS_BUILD_DIR -E Zend --gcov-options '\-lp'

notifications:
email: false